#!/usr/bin/env bash

echo "pre-commit hook"
echo "** ARG **"
echo "$# args, $*"
readonly SCRIPT_NAME=$(basename "$0")
readonly SCRIPT_PATH=${0}
# shellcheck disable=SC2034
readonly SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
echo "\$SCRIPT_NAME=$SCRIPT_NAME"
echo "\$SCRIPT_PATH=$SCRIPT_PATH"
echo "\$SCRIPT_DIR=$SCRIPT_DIR"
echo "PWD=$(pwd)"
echo "** ENV **"
env
echo "$# args, $*"

exit 1